const { default: mongoose } = require("mongoose");

const ListingModel = mongoose.Schema({
  soldOut: { type: Boolean, required: true },
  id: { type: String, unique: true, required: true },
  fullName: { type: String, required: true },
  email: { type: String, required: true },
  phoneNumber: { type: Number, required: true },
  title: { type: String, required: true },
  shortDescription: { type: String, required: true },
  detailDescription: { type: String, required: true },
  websiteURL: { type: String, unique: true, required: true },
  websiteRegistrationDate: { type: String, required: true },
  websiteName: { type: String, required: true },
  websiteCategory: { type: String, required: true },
  websitePlatform: { type: String, required: true },
  domainSeller: { type: String, required: true },
  domainRegistrationDate: { type: String, required: true },
  domainRenewalDate: { type: String, required: true },
  domainKeywords: { type: String, required: true },
  hostingPlatform: { type: String, required: true },
  isWebsiteMonetized: { type: String, required: true },
  monetizationPlatform: { type: String, required: true },
  websiteMonetizationDate: { type: String, required: true },
  monetizationCountry: { type: String, required: true },
  pinVerified: { type: String, required: true },
  lastMonthTraffic: { type: Number, required: true },
  lastSixMonthTraffic: { type: Number, required: true },
  lastMonthEarnings: { type: Number, required: true },
  paymentReceived: { type: String, required: true },
  lastSixMonthEarnings: { type: Number, required: true },
  domainSellingPrice: { type: Number, required: true },
});

module.exports = mongoose.model("ListingModel", ListingModel);
